
#include <string.h>
#include <stdlib.h>
#include <malloc.h>
#include <utilCommands.h>
#include <bufferedInputHandler.h>
#include "neopixelCommands.h"
#include "bluetoothATConfig.h"
#include "systick.h"
#include "stringFunctions.h"
#include "neopixelDriver.h"
#include "uart.h"
#include "datetimeClock.h"
#include "consoleBase.h"
/**
 * @brief prints a brief overview of the commands
 * 
 * @param cmd the command, doesn't take any arguments
 * @param context unused
 */
void helpCommand(char * cmd,void* context)
{
	printf("Supported basic commands are\r\n");
	printf(" * API: switches physical interface to api mode, does not echo character and does not allow \r\n");
	printf("   command line editing and history\r\n");
	printf(" * CONSOLE: switches the physical interface to console mode, characters received are echoed\r\n");
	printf("   also command line history and editing is possible\r\n");
	printf(" * SYSINFO: displays system and memory infos\r\n");
	printf(" * SETDT: sets date and time of the RTC, format is SETDT(year,month,day,hour,minute,second)\r\n");
	printf("   with year as 4-digit year, month and day starting at 1 and hour, minute,second, starting at 0, all number shouls\r\n");
	printf("   be entered as integers without leading zeros\r\n");
}



/**
 * @brief switches the mode of the interface to API. Nothing happens if the mode is already API.
 * 
 * Note: it is only possible to change the mode of the interface which is accessed.
 * @param cmd the command, doesn't taken any arguments, therefore unused here.
 * @param context the BufferedInput from which the command has been sent.
 */
void apiCommand(char * cmd,void* context)
{
	BufferedInput binput = (BufferedInput)context;
	binput->interfaceType = BINPUT_TYPE_API;
	printf("APIOK\n");
	binput->console->outBfr[0]=0; // disable command prompt already generated by the console handler
}

/**
 * @brief switches the mode of the interface to Console/CLI. Nothing happens if the mode is already Console/CLI.
 * 
 * @param cmd the command, doesn't taken any arguments, therefore unused here.
 * @param context the BufferedInput from which the command has been sent.
 */
void consoleCommand(char * cmd,void* context)
{
	BufferedInput binput = (BufferedInput)context;
	binput->interfaceType = BINPUT_TYPE_CONSOLE;
	printf("Switching back to Console Mode\r\n");
}


/**
 * @brief prints out system information
 * 
 * @param cmd the command, doesn't taken any arguments, therefore unused here.
 * @param context unused
 */
void sysInfoCommand(char * cmd,void*context)
{
	uint32_t current_sp = (uint32_t)address;
	struct mallinfo heapInfo;
	uint32_t nticks;
	char nrbfr[32];
	heapInfo = mallinfo();
	nticks = getTickValue();
	printf("\r\n\r\nTicks since Start: ");
	UInt32ToChar(nticks,nrbfr);
	printf(nrbfr);
	printf("\r\n");
	printf("Date and Time: ");
	dateTimeToString(nrbfr,getYear(),getMonth(),getDay(),getHour(),getMinute(),getSecond());
	printf(nrbfr);
	printf("\r\n");
	printf("Current Stack Pointer Location (bytes): ");
	UInt32ToHex(current_sp,nrbfr);
	printf(nrbfr);
	printf("\r\n");
	printf("Total Allocated Space (bytes): ");
	UInt32ToChar((uint32_t)heapInfo.uordblks,nrbfr);
	printf(nrbfr);
	printf("\r\n");
	printf("Total Free Space (bytes): ");
	UInt32ToChar((uint32_t)heapInfo.fordblks,nrbfr);
	printf(nrbfr);
	printf("\r\n");
}


void setDateTimeCommand(char* cmd,void*context)
{
	char bfr[32];
	char nrbfrArray[8];
	char * nrbfr = nrbfrArray;
	uint16_t v2;
	uint8_t v1;
	getBracketContent(cmd,bfr);
	nrbfr = strtok(bfr,",");
	v2 = toUInt16(nrbfr);
	setYear(v2);
	nrbfr = strtok(0,",");
	v1 = toUInt8(nrbfr);
	setMonth(v1);
	nrbfr = strtok(0,",");
	v1 = toUInt8(nrbfr);
	setDay(v1);
	nrbfr = strtok(0,",");
	v1 = toUInt8(nrbfr);
	setHour(v1);
	nrbfr = strtok(0,",");
	v1 = toUInt8(nrbfr);
	setMinute(v1);
	nrbfr = strtok(0,",");
	v1 = toUInt8(nrbfr);
	setSecond(v1);
}